# Generated by Django 3.2.5 on 2023-06-22 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('postcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResidentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=1000)),
                ('contact', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('postcode', models.IntegerField()),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('isLeader', models.BooleanField(default=False)),
                ('groupID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.neighborhoodgroupmodel')),
            ],
        ),
    ]
