# Generated by Django 3.2.5 on 2023-06-24 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0003_alter_neighborhoodgroupmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.neighborhoodgroupmodel')),
                ('residentID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.residentmodel')),
            ],
        ),
    ]
