# Generated by Django 3.2.5 on 2023-06-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0006_alter_neighborhoodgroupmodel_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhoodgroupmodel',
            name='rules',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
