# Generated by Django 3.2.5 on 2023-06-25 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0007_alter_neighborhoodgroupmodel_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('authorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.residentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EventPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('participants', models.CharField(default='', max_length=1000)),
                ('organizerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.residentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CrimePostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('actions', models.CharField(max_length=2000)),
                ('reporterID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.residentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('target', models.CharField(max_length=100)),
                ('isAnonymous', models.BooleanField(default=False)),
                ('reporterID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.residentmodel')),
            ],
        ),
    ]
