# Generated by Django 3.2.5 on 2023-06-28 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0008_complaintpostmodel_crimepostmodel_eventpostmodel_generalpostmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpostmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='eventpostmodel',
            name='time',
        ),
        migrations.AddField(
            model_name='eventpostmodel',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
