# Generated by Django 3.2.5 on 2023-06-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0009_auto_20230628_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimepostmodel',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventpostmodel',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
