# Generated by Django 3.2.5 on 2023-06-29 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0010_auto_20230628_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPostCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=2000)),
                ('authorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.residentmodel')),
                ('postID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.generalpostmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EventPostCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=2000)),
                ('authorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.residentmodel')),
                ('postID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.eventpostmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CrimePostCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=2000)),
                ('authorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.residentmodel')),
                ('postID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.crimepostmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintPostCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=2000)),
                ('authorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.residentmodel')),
                ('postID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.complaintpostmodel')),
            ],
        ),
    ]
