# Generated by Django 3.2.5 on 2023-06-29 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0011_complaintpostcommentmodel_crimepostcommentmodel_eventpostcommentmodel_generalpostcommentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=100)),
                ('groupID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.neighborhoodgroupmodel')),
                ('holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAPI.residentmodel')),
            ],
        ),
    ]
