# Generated by Django 3.2.5 on 2023-06-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0012_facilitiesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintpostmodel',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaintpostmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crimepostmodel',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crimepostmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventpostmodel',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventpostmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalpostmodel',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalpostmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='residentmodel',
            name='userData',
            field=models.CharField(default="{'crimePostLikes': [],'crimePostDislikes': [],'complaintPostLikes': [],'complaintPostDislikes': [],'eventPostLikes': [],'eventPostDislikes': [],'generalPostLikes': [],'generalPostDislikes': []}", max_length=1000),
        ),
    ]
