# Generated by Django 3.2.5 on 2023-06-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0013_auto_20230630_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentmodel',
            name='userData',
            field=models.CharField(default='{"crimePostLikes": [],"crimePostDislikes": [],"complaintPostLikes": [],"complaintPostDislikes": [],"eventPostLikes": [],"eventPostDislikes": [],"generalPostLikes": [],"generalPostDislikes": []}', max_length=1000),
        ),
    ]
