# Generated by Django 3.2.5 on 2023-07-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0014_alter_residentmodel_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintpostmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/complaint'),
        ),
        migrations.AddField(
            model_name='eventpostmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/event'),
        ),
        migrations.AddField(
            model_name='generalpostmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/general'),
        ),
        migrations.AlterField(
            model_name='crimepostmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/crime'),
        ),
    ]
