# Generated by Django 3.2.5 on 2023-07-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0015_auto_20230711_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/profile'),
        ),
    ]
