# Generated by Django 3.2.5 on 2023-07-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0016_residentmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintpostcommentmodel',
            name='authorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RESTAPI.residentmodel'),
        ),
        migrations.AlterField(
            model_name='complaintpostcommentmodel',
            name='postID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RESTAPI.complaintpostmodel'),
        ),
        migrations.AlterField(
            model_name='crimepostcommentmodel',
            name='authorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RESTAPI.residentmodel'),
        ),
        migrations.AlterField(
            model_name='crimepostcommentmodel',
            name='postID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RESTAPI.crimepostmodel'),
        ),
        migrations.AlterField(
            model_name='eventpostcommentmodel',
            name='authorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RESTAPI.residentmodel'),
        ),
        migrations.AlterField(
            model_name='eventpostcommentmodel',
            name='postID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RESTAPI.eventpostmodel'),
        ),
        migrations.AlterField(
            model_name='generalpostcommentmodel',
            name='authorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RESTAPI.residentmodel'),
        ),
        migrations.AlterField(
            model_name='generalpostcommentmodel',
            name='postID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RESTAPI.generalpostmodel'),
        ),
    ]
